create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Athlete',
  height_cm numeric,
  current_weight_kg numeric,
  age integer,
  sex text,
  goal_type text,
  target_weight_kg numeric,
  target_date date,
  activity_level text,
  experience_level text,
  training_days integer check (training_days between 2 and 6),
  session_minutes integer,
  equipment_access text,
  limitation_notes text,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  primary_muscle text not null,
  equipment text not null,
  equipment_name text,
  mechanic text,
  difficulty text not null default 'beginner',
  cues text[] not null default '{}',
  secondary_muscles text[] not null default '{}',
  instructions text[] not null default '{}',
  image_url text,
  image_url_2 text,
  video_url text,
  created_at timestamptz not null default now()
);

alter table public.exercises add column if not exists equipment_name text;
alter table public.exercises add column if not exists mechanic text;
alter table public.exercises add column if not exists secondary_muscles text[] not null default '{}';
alter table public.exercises add column if not exists instructions text[] not null default '{}';
alter table public.exercises add column if not exists image_url text;
alter table public.exercises add column if not exists image_url_2 text;
alter table public.exercises add column if not exists video_url text;
alter table public.exercises enable row level security;

insert into public.exercises
  (name, primary_muscle, equipment, difficulty, cues, secondary_muscles, instructions, mechanic, equipment_name, image_url, image_url_2)
values
  ('Barbell Bench Press', 'chest', 'full_gym', 'beginner', '{}', '{"shoulders","triceps"}', '{"Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.","From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.","After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.","Repeat the movement for the prescribed amount of repetitions.","When you are done, place the bar back in the rack."}', 'compound', 'Barbell', '/exercises/barbell-bench-press/0.jpg', '/exercises/barbell-bench-press/1.jpg'),
  ('Incline Barbell Press', 'chest', 'full_gym', 'beginner', '{}', '{"shoulders","triceps"}', '{"Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.","As you breathe in, come down slowly until you feel the bar on you upper chest.","After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly again. Tip: it should take at least twice as long to go down than to come up.","Repeat the movement for the prescribed amount of repetitions.","When you are done, place the bar back in the rack."}', 'compound', 'Barbell', '/exercises/incline-barbell-press/0.jpg', '/exercises/incline-barbell-press/1.jpg'),
  ('Dumbbell Bench Press', 'chest', 'home_basic', 'beginner', '{}', '{"shoulders","triceps"}', '{"Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.","Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.","Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.","Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it.","Repeat the movement for the prescribed amount of repetitions of your training program."}', 'compound', 'Dumbbell', '/exercises/dumbbell-bench-press/0.jpg', '/exercises/dumbbell-bench-press/1.jpg'),
  ('Incline Dumbbell Press', 'chest', 'home_basic', 'beginner', '{}', '{"shoulders","triceps"}', '{"Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.","Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.","Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.","Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.","Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.","Repeat the movement for the prescribed amount of repetitions."}', 'compound', 'Dumbbell', '/exercises/incline-dumbbell-press/0.jpg', '/exercises/incline-dumbbell-press/1.jpg'),
  ('Dumbbell Fly', 'chest', 'home_basic', 'beginner', '{}', '{}', '{"Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.","Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you''re pressing them, but stop and hold just before you lock out. This will be your starting position.","With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.","Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.","Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/dumbbell-fly/0.jpg', '/exercises/dumbbell-fly/1.jpg'),
  ('Cable Crossover', 'chest', 'full_gym', 'beginner', '{}', '{"shoulders"}', '{"To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.","Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.","With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.","Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.","Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions."}', 'isolation', 'Cable', '/exercises/cable-crossover/0.jpg', '/exercises/cable-crossover/1.jpg'),
  ('Machine Chest Press', 'chest', 'full_gym', 'beginner', '{}', '{"shoulders","triceps"}', '{"Sit down on the Chest Press Machine and select the weight.","Step on the lever provided by the machine since it will help you to bring the handles forward so that you can grab the handles and fully extend the arms.","Grab the handles with a palms-down grip and lift your elbows so that your upper arms are parallel to the floor to the sides of your torso. Tip: Your forearms will be pointing forward since you are grabbing the handles. Once you bring the handles forward and extend the arms you will be at the starting position.","Now bring the handles back towards you as you breathe in.","Push the handles away from you as you flex your pecs and you breathe out. Hold the contraction for a second before going back to the starting position.","Repeat for the recommended amount of reps."}', 'compound', 'Machine', '/exercises/machine-chest-press/0.jpg', '/exercises/machine-chest-press/1.jpg'),
  ('Push-Up', 'chest', 'bodyweight', 'beginner', '{}', '{"shoulders","triceps"}', '{"Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.","Next, lower yourself downward until your chest almost touches the floor as you inhale.","Now breathe out and press your upper body back up to the starting position while squeezing your chest.","After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed."}', 'compound', 'Bodyweight', '/exercises/push-up/0.jpg', '/exercises/push-up/1.jpg'),
  ('Wide Push-Up', 'chest', 'bodyweight', 'beginner', '{}', '{"core","shoulders","triceps"}', '{"With your hands wide apart, support your body on your toes and hands in a plank position. Your elbows should be extended and your body straight. Do not allow your hips to sag. This will be your starting position.","To begin, allow the elbows to flex, lowering your chest to the floor as you inhale.","Using your pectoral muscles, press your upper body back up to the starting position by extending the elbows. Exhale as you perform this step.","After pausing at the contracted position, repeat the movement for the prescribed amount of repetitions."}', 'compound', 'Bodyweight', '/exercises/wide-push-up/0.jpg', '/exercises/wide-push-up/1.jpg'),
  ('Deadlift', 'back', 'full_gym', 'intermediate', '{}', '{"calves","forearms","glutes","hamstrings","quads","traps"}', '{"Stand in front of a loaded barbell.","While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.","While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.","Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition.","Perform the amount of repetitions prescribed in the program."}', 'compound', 'Barbell', '/exercises/deadlift/0.jpg', '/exercises/deadlift/1.jpg'),
  ('Bent-Over Barbell Row', 'back', 'full_gym', 'beginner', '{}', '{"biceps","shoulders"}', '{"Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.","Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.","Then inhale and slowly lower the barbell back to the starting position.","Repeat for the recommended amount of repetitions."}', 'compound', 'Barbell', '/exercises/bent-over-barbell-row/0.jpg', '/exercises/bent-over-barbell-row/1.jpg'),
  ('One-Arm Dumbbell Row', 'back', 'home_basic', 'beginner', '{}', '{"biceps","shoulders"}', '{"Choose a flat bench and place a dumbbell on each side of it.","Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.","Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.","Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.","Lower the resistance straight down to the starting position. Breathe in as you perform this step.","Repeat the movement for the specified amount of repetitions."}', 'compound', 'Dumbbell', '/exercises/one-arm-dumbbell-row/0.jpg', '/exercises/one-arm-dumbbell-row/1.jpg'),
  ('Seated Cable Row', 'back', 'full_gym', 'beginner', '{}', '{"biceps","shoulders"}', '{"For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.","Lean over as you keep the natural alignment of your back and grab the V-bar handles.","With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.","Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.","Repeat for the recommended amount of repetitions."}', 'compound', 'Cable', '/exercises/seated-cable-row/0.jpg', '/exercises/seated-cable-row/1.jpg'),
  ('Lat Pulldown', 'back', 'full_gym', 'beginner', '{}', '{"biceps","shoulders"}', '{"Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.","Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.","As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.","As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.","After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.","Repeat this motion for the prescribed amount of repetitions."}', 'compound', 'Cable', '/exercises/lat-pulldown/0.jpg', '/exercises/lat-pulldown/1.jpg'),
  ('Close-Grip Pulldown', 'back', 'full_gym', 'beginner', '{}', '{"biceps","shoulders"}', '{"Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.","Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.","As you have both arms extended in front of you - while holding the bar at the chosen grip width - bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.","As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary (only the arms should move). The forearms should do no other work except for holding the bar; therefore do not try to pull the bar down using the forearms.","After a second in the contracted position, while squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.","Repeat this motion for the prescribed amount of repetitions."}', 'compound', 'Cable', '/exercises/close-grip-pulldown/0.jpg', '/exercises/close-grip-pulldown/1.jpg'),
  ('Straight-Arm Pulldown', 'back', 'full_gym', 'beginner', '{}', '{}', '{"You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.","Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.","While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.","While keeping the arms straight, go back to the starting position while breathing in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Cable', '/exercises/straight-arm-pulldown/0.jpg', '/exercises/straight-arm-pulldown/1.jpg'),
  ('Pull-Up', 'back', 'bodyweight', 'beginner', '{}', '{"biceps"}', '{"Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.","As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.","Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.","After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.","Repeat this motion for the prescribed amount of repetitions."}', 'compound', 'Bodyweight', '/exercises/pull-up/0.jpg', '/exercises/pull-up/1.jpg'),
  ('Chin-Up', 'back', 'bodyweight', 'beginner', '{}', '{"biceps","forearms"}', '{"Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width.","As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement.","As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.","After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you perform this portion of the movement.","Repeat this motion for the prescribed amount of repetitions."}', 'compound', 'Bodyweight', '/exercises/chin-up/0.jpg', '/exercises/chin-up/1.jpg'),
  ('T-Bar Row', 'back', 'full_gym', 'beginner', '{}', '{"biceps"}', '{"Position a bar into a landmine or in a corner to keep it from moving. Load an appropriate weight onto your end.","Stand over the bar, and position a Double D row handle around the bar next to the collar. Using your hips and legs, rise to a standing position.","Assume a wide stance with your hips back and your chest up. Your arms should be extended. This will be your starting position.","Pull the weight to your upper abdomen by retracting the shoulder blades and flexing the elbows. Do not jerk the weight or cheat during the movement.","After a brief pause, return to the starting position."}', 'compound', 'Barbell', '/exercises/t-bar-row/0.jpg', '/exercises/t-bar-row/1.jpg'),
  ('Overhead Barbell Press', 'shoulders', 'full_gym', 'intermediate', '{}', '{"chest","triceps"}', '{"Sit on a bench with back support in a squat rack. Position a barbell at a height that is just above your head. Grab the barbell with a pronated grip (palms facing forward).","Once you pick up the barbell with the correct grip width, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.","Lower the bar down to the shoulders slowly as you inhale.","Lift the bar back up to the starting position as you exhale.","Repeat for the recommended amount of repetitions."}', 'compound', 'Barbell', '/exercises/overhead-barbell-press/0.jpg', '/exercises/overhead-barbell-press/1.jpg'),
  ('Dumbbell Shoulder Press', 'shoulders', 'home_basic', 'intermediate', '{}', '{"triceps"}', '{"While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.","Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.","Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.","Now, exhale and push the dumbbells upward until they touch at the top.","Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.","Repeat for the recommended amount of repetitions."}', 'compound', 'Dumbbell', '/exercises/dumbbell-shoulder-press/0.jpg', '/exercises/dumbbell-shoulder-press/1.jpg'),
  ('Arnold Press', 'shoulders', 'home_basic', 'intermediate', '{}', '{"triceps"}', '{"Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. Tip: Your arms should be next to your torso. The starting position should look like the contracted portion of a dumbbell curl.","Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward.","Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement.","After a second pause at the top, begin to lower the dumbbells to the original position by rotating the palms of your hands towards you. Tip: The left arm will be rotated in a counter clockwise manner while the right one will be rotated clockwise. Breathe in as you perform this portion of the movement.","Repeat for the recommended amount of repetitions."}', 'compound', 'Dumbbell', '/exercises/arnold-press/0.jpg', '/exercises/arnold-press/1.jpg'),
  ('Dumbbell Lateral Raise', 'shoulders', 'home_basic', 'beginner', '{}', '{}', '{"Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.","While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.","Lower the dumbbells back down slowly to the starting position as you inhale.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/dumbbell-lateral-raise/0.jpg', '/exercises/dumbbell-lateral-raise/1.jpg'),
  ('Front Raise', 'shoulders', 'home_basic', 'beginner', '{}', '{}', '{"Pick a couple of dumbbells and stand with a straight torso and the dumbbells on front of your thighs at arms length with the palms of the hand facing your thighs. This will be your starting position.","While maintaining the torso stationary (no swinging), lift the left dumbbell to the front with a slight bend on the elbow and the palms of the hands always facing down. Continue to go up until you arm is slightly above parallel to the floor. Exhale as you execute this portion of the movement and pause for a second at the top. Inhale after the second pause.","Now lower the dumbbell back down slowly to the starting position as you simultaneously lift the right dumbbell.","Continue alternating in this fashion until all of the recommended amount of repetitions have been performed for each arm."}', 'isolation', 'Dumbbell', '/exercises/front-raise/0.jpg', '/exercises/front-raise/1.jpg'),
  ('Reverse Fly', 'shoulders', 'home_basic', 'beginner', '{}', '{}', '{"To begin, lie down on an incline bench with the chest and stomach pressing against the incline. Have the dumbbells in each hand with the palms facing each other (neutral grip).","Extend the arms in front of you so that they are perpendicular to the angle of the bench. The legs should be stationary while applying pressure with the ball of your toes. This is the starting position.","Maintaining the slight bend of the elbows, move the weights out and away from each other (to the side) in an arc motion while exhaling. Tip: Try to squeeze your shoulder blades together to get the best results from this exercise.","The arms should be elevated until they are parallel to the floor.","Feel the contraction and slowly lower the weights back down to the starting position while inhaling.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/reverse-fly/0.jpg', '/exercises/reverse-fly/1.jpg'),
  ('Face Pull', 'shoulders', 'full_gym', 'intermediate', '{}', '{"back"}', '{"Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground."}', 'compound', 'Cable', '/exercises/face-pull/0.jpg', '/exercises/face-pull/1.jpg'),
  ('Barbell Shrug', 'traps', 'full_gym', 'beginner', '{}', '{}', '{"Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for a better grip. This will be your starting position.","Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps.","Slowly return to the starting position as you breathe in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Barbell', '/exercises/barbell-shrug/0.jpg', '/exercises/barbell-shrug/1.jpg'),
  ('Dumbbell Shrug', 'traps', 'home_basic', 'beginner', '{}', '{}', '{"Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides.","Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down.","Lower the dumbbells back to the original position.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/dumbbell-shrug/0.jpg', '/exercises/dumbbell-shrug/1.jpg'),
  ('Triceps Pushdown', 'triceps', 'full_gym', 'beginner', '{}', '{}', '{"Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.","Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.","Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.","After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Cable', '/exercises/triceps-pushdown/0.jpg', '/exercises/triceps-pushdown/1.jpg'),
  ('Rope Triceps Pushdown', 'triceps', 'full_gym', 'beginner', '{}', '{}', '{"Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other).","Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the rope with the palms facing each other. This is your starting position.","Using the triceps, bring the rope down as you bring each side of the rope to the side of your thighs. At the end of the movement the arms are fully extended and perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.","After holding for a second, at the contracted position, bring the rope slowly up to the starting point. Breathe in as you perform this step.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Cable', '/exercises/rope-triceps-pushdown/0.jpg', '/exercises/rope-triceps-pushdown/1.jpg'),
  ('Overhead Rope Extension', 'triceps', 'full_gym', 'beginner', '{}', '{}', '{"Attach a rope to the bottom pulley of the pulley machine.","Grasping the rope with both hands, extend your arms with your hands directly above your head using a neutral grip (palms facing each other). Your elbows should be in close to your head and the arms should be perpendicular to the floor with the knuckles aimed at the ceiling. This will be your starting position.","Slowly lower the rope behind your head as you hold the upper arms stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.","Return to the starting position by flexing your triceps as you breathe out.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Cable', '/exercises/overhead-rope-extension/0.jpg', '/exercises/overhead-rope-extension/1.jpg'),
  ('Close-Grip Bench Press', 'triceps', 'full_gym', 'beginner', '{}', '{"chest","shoulders"}', '{"Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.","As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement.","After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.","Repeat the movement for the prescribed amount of repetitions.","When you are done, place the bar back in the rack."}', 'compound', 'Barbell', '/exercises/close-grip-bench-press/0.jpg', '/exercises/close-grip-bench-press/1.jpg'),
  ('Skull Crusher', 'triceps', 'full_gym', 'beginner', '{}', '{"forearms"}', '{"Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position.","Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.","Lift the bar back to the starting position by extending the elbow and exhaling.","Repeat."}', 'isolation', 'EZ-bar', '/exercises/skull-crusher/0.jpg', '/exercises/skull-crusher/1.jpg'),
  ('Lying Dumbbell Extension', 'triceps', 'home_basic', 'intermediate', '{}', '{"chest","shoulders"}', '{"Lie on a flat bench while holding two dumbbells directly in front of you. Your arms should be fully extended at a 90-degree angle from your torso and the floor. The palms should be facing in and the elbows should be tucked in. This is the starting position.","As you breathe in and you keep the upper arms stationary with the elbows in, slowly lower the weight until the dumbbells are near your ears.","At that point, while keeping the elbows in and the upper arms stationary, use the triceps to bring the weight back up to the starting position as you breathe out.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/lying-dumbbell-extension/0.jpg', '/exercises/lying-dumbbell-extension/1.jpg'),
  ('Overhead Dumbbell Extension', 'triceps', 'home_basic', 'beginner', '{}', '{}', '{"To begin, stand up with a dumbbell held by both hands. Your feet should be about shoulder width apart from each other. Slowly use both hands to grab the dumbbell and lift it over your head until both arms are fully extended.","The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hands should be facing up towards the ceiling. This will be your starting position.","Keeping your upper arms close to your head with elbows in and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.","Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/overhead-dumbbell-extension/0.jpg', '/exercises/overhead-dumbbell-extension/1.jpg'),
  ('Triceps Kickback', 'triceps', 'home_basic', 'beginner', '{}', '{}', '{"Start with a dumbbell in each hand and your palms facing your torso. Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor. Make sure to keep your head up. Your upper arms should be close to your torso and parallel to the floor. Your forearms should be pointed towards the floor as you hold the weights. There should be a 90-degree angle formed between your forearm and upper arm. This is your starting position.","Now, while keeping your upper arms stationary, exhale and use your triceps to lift the weights until the arm is fully extended. Focus on moving the forearm.","After a brief pause at the top contraction, inhale and slowly lower the dumbbells back down to the starting position.","Repeat the movement for the prescribed amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/triceps-kickback/0.jpg', '/exercises/triceps-kickback/1.jpg'),
  ('Bench Dip', 'triceps', 'bodyweight', 'beginner', '{}', '{"chest","shoulders"}', '{"For this exercise you will need to place a bench behind your back. With the bench perpendicular to your body, and while looking away from it, hold on to the bench on its edge with the hands fully extended, separated at shoulder width. The legs will be extended forward, bent at the waist and perpendicular to your torso. This will be your starting position.","Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible throughout the movement. Forearms should always be pointing down.","Using your triceps to bring your torso up again, lift yourself back to the starting position.","Repeat for the recommended amount of repetitions."}', 'compound', 'Bodyweight', '/exercises/bench-dip/0.jpg', '/exercises/bench-dip/1.jpg'),
  ('Triceps Dip', 'triceps', 'bodyweight', 'beginner', '{}', '{"chest","shoulders"}', '{"To get into the starting position, hold your body at arm''s length with your arms nearly locked above the bars.","Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm.","Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.","Repeat the movement for the prescribed amount of repetitions."}', 'compound', 'Bodyweight', '/exercises/triceps-dip/0.jpg', '/exercises/triceps-dip/1.jpg'),
  ('Barbell Curl', 'biceps', 'full_gym', 'beginner', '{}', '{"forearms"}', '{"Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.","While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.","Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.","Slowly begin to bring the bar back to starting position as your breathe in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Barbell', '/exercises/barbell-curl/0.jpg', '/exercises/barbell-curl/1.jpg'),
  ('Dumbbell Curl', 'biceps', 'home_basic', 'beginner', '{}', '{"forearms"}', '{"Stand up straight with a dumbbell in each hand at arm''s length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.","Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.","Then, inhale and slowly begin to lower the dumbbells back to the starting position.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/dumbbell-curl/0.jpg', '/exercises/dumbbell-curl/1.jpg'),
  ('Alternating Dumbbell Curl', 'biceps', 'home_basic', 'beginner', '{}', '{"forearms"}', '{"Stand (torso upright) with a dumbbell in each hand held at arms length. The elbows should be close to the torso and the palms of your hand should be facing your thighs.","While holding the upper arm stationary, curl the right weight as you rotate the palm of the hands until they are facing forward. At this point continue contracting the biceps as you breathe out until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.","Slowly begin to bring the dumbbell back to the starting position as your breathe in. Tip: Remember to twist the palms back to the starting position (facing your thighs) as you come down.","Repeat the movement with the left hand. This equals one repetition.","Continue alternating in this manner for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/alternating-dumbbell-curl/0.jpg', '/exercises/alternating-dumbbell-curl/1.jpg'),
  ('Hammer Curl', 'biceps', 'home_basic', 'beginner', '{}', '{}', '{"Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.","The palms of the hands should be facing your torso. This will be your starting position.","Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm.","After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/hammer-curl/0.jpg', '/exercises/hammer-curl/1.jpg'),
  ('Preacher Curl', 'biceps', 'full_gym', 'beginner', '{}', '{}', '{"To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.","With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.","As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.","As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Barbell', '/exercises/preacher-curl/0.jpg', '/exercises/preacher-curl/1.jpg'),
  ('Incline Dumbbell Curl', 'biceps', 'home_basic', 'beginner', '{}', '{}', '{"Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.","While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.","Slowly begin to bring the dumbbells back to starting position as your breathe in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Dumbbell', '/exercises/incline-dumbbell-curl/0.jpg', '/exercises/incline-dumbbell-curl/1.jpg'),
  ('Concentration Curl', 'biceps', 'home_basic', 'beginner', '{}', '{"forearms"}', '{"Sit down on a flat bench with one dumbbell in front of you between your legs. Your legs should be spread with your knees bent and feet on the floor.","Use your right arm to pick the dumbbell up. Place the back of your right upper arm on the top of your inner right thigh. Rotate the palm of your hand until it is facing forward away from your thigh. Tip: Your arm should be extended and the dumbbell should be above the floor. This will be your starting position.","While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Tip: At the top of the movement make sure that the little finger of your arm is higher than your thumb. This guarantees a good contraction. Hold the contracted position for a second as you squeeze the biceps.","Slowly begin to bring the dumbbells back to starting position as your breathe in. Caution: Avoid swinging motions at any time.","Repeat for the recommended amount of repetitions. Then repeat the movement with the left arm."}', 'isolation', 'Dumbbell', '/exercises/concentration-curl/0.jpg', '/exercises/concentration-curl/1.jpg'),
  ('Cable Curl', 'biceps', 'full_gym', 'beginner', '{}', '{}', '{"Stand up with your torso upright while holding a cable curl bar that is attached to a low pulley. Grab the cable bar at shoulder width and keep the elbows close to the torso. The palm of your hands should be facing up (supinated grip). This will be your starting position.","While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.","Slowly begin to bring the curl bar back to starting position as your breathe in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Cable', '/exercises/cable-curl/0.jpg', '/exercises/cable-curl/1.jpg'),
  ('Spider Curl', 'biceps', 'full_gym', 'beginner', '{}', '{}', '{"Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off.","Move to the front side of the preacher bench (the part where the arms usually lay) and position yourself to lay at a 45 degree slant with your torso and stomach pressed against the front side of the preacher bench.","Make sure that your feet (especially the toes) are well positioned on the floor and place your upper arms on top of the pad located on the inside part of the preacher bench.","Use your arms to grab the barbell with a supinated grip (palms facing up) at about shoulder width apart or slightly closer from each other.","Slowly begin to lift the barbell upwards and exhale. Hold the contracted position for a second as you squeeze the biceps.","Slowly begin to bring the barbell back to the starting position as your breathe in. ."}', 'isolation', 'EZ-bar', '/exercises/spider-curl/0.jpg', '/exercises/spider-curl/1.jpg'),
  ('Back Squat', 'quads', 'full_gym', 'intermediate', '{}', '{"calves","glutes","hamstrings","back"}', '{"This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.","Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.","Step away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times and maintain a straight back. This will be your starting position.","Begin to slowly lower the bar by bending the knees and sitting back with your hips as you maintain a straight posture with the head up. Continue down until your hamstrings are on your calves. Inhale as you perform this portion of the movement.","Begin to raise the bar as you exhale by pushing the floor with the heel or middle of your foot as you straighten the legs and extend the hips to go back to the starting position.","Repeat for the recommended amount of repetitions."}', 'compound', 'Barbell', '/exercises/back-squat/0.jpg', '/exercises/back-squat/1.jpg'),
  ('Front Squat', 'quads', 'full_gym', 'expert', '{}', '{"calves","glutes","hamstrings"}', '{"This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control.","Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso.","Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).","Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.","Begin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.","Repeat for the recommended amount of repetitions."}', 'compound', 'Barbell', '/exercises/front-squat/0.jpg', '/exercises/front-squat/1.jpg'),
  ('Goblet Squat', 'quads', 'home_basic', 'beginner', '{}', '{"calves","glutes","hamstrings","shoulders"}', '{"Stand holding a light kettlebell by the horns close to your chest. This will be your starting position.","Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight.","At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions."}', 'compound', 'Kettlebell', '/exercises/goblet-squat/0.jpg', '/exercises/goblet-squat/1.jpg'),
  ('Bodyweight Squat', 'quads', 'bodyweight', 'beginner', '{}', '{"glutes","hamstrings"}', '{"Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position.","Begin the movement by flexing your knees and hips, sitting back with your hips.","Continue down to full depth if you are able,and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out."}', 'compound', 'Bodyweight', '/exercises/bodyweight-squat/0.jpg', '/exercises/bodyweight-squat/1.jpg'),
  ('Leg Press', 'quads', 'full_gym', 'beginner', '{}', '{"calves","glutes","hamstrings"}', '{"Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).","Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.","As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.","Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.","Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."}', 'compound', 'Machine', '/exercises/leg-press/0.jpg', '/exercises/leg-press/1.jpg'),
  ('Leg Extension', 'quads', 'full_gym', 'beginner', '{}', '{}', '{"For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position. Tip: You will need to adjust the pad so that it falls on top of your lower leg (just above your feet). Also, make sure that your legs form a 90-degree angle between the lower and upper leg. If the angle is less than 90-degrees then that means the knee is over the toes which in turn creates undue stress at the knee joint. If the machine is designed that way, either look for another machine or just make sure that when you start executing the exercise you stop going down once you hit the 90-degree angle.","Using your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position.","Slowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit.","Repeat for the recommended amount of times."}', 'isolation', 'Machine', '/exercises/leg-extension/0.jpg', '/exercises/leg-extension/1.jpg'),
  ('Walking Lunge', 'quads', 'home_basic', 'beginner', '{}', '{"calves","glutes","hamstrings"}', '{"Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.","Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Note: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground.","Using mainly the heel of your foot, push up and go back to the starting position as you exhale.","Repeat the movement for the recommended amount of repetitions and then perform with the left leg."}', 'compound', 'Dumbbell', '/exercises/walking-lunge/0.jpg', '/exercises/walking-lunge/1.jpg'),
  ('Reverse Lunge', 'quads', 'home_basic', 'intermediate', '{}', '{"calves","glutes","hamstrings"}', '{"Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.","Step backward with your right leg around two feet or so from the left foot and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Tip: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground. Keep the torso upright during the lunge; flexible hip flexors are important. A long lunge emphasizes the Gluteus Maximus; a short lunge emphasizes Quadriceps.","Push up and go back to the starting position as you exhale. Tip: Use the ball of your feet to push in order to accentuate the quadriceps. To focus on the glutes, press with your heels.","Now repeat with the opposite leg."}', 'compound', 'Dumbbell', '/exercises/reverse-lunge/0.jpg', '/exercises/reverse-lunge/1.jpg'),
  ('Romanian Deadlift', 'hamstrings', 'full_gym', 'intermediate', '{}', '{"calves","glutes","back"}', '{"Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.","Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.","Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.","Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.","Repeat for the recommended amount of repetitions."}', 'compound', 'Barbell', '/exercises/romanian-deadlift/0.jpg', '/exercises/romanian-deadlift/1.jpg'),
  ('Lying Leg Curl', 'hamstrings', 'full_gym', 'beginner', '{}', '{}', '{"Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.","Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.","As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.","As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions."}', 'isolation', 'Machine', '/exercises/lying-leg-curl/0.jpg', '/exercises/lying-leg-curl/1.jpg'),
  ('Seated Leg Curl', 'hamstrings', 'full_gym', 'beginner', '{}', '{}', '{"Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad.","Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees. Then grasp the side handles on the machine as you point your toes straight (or you can also use any of the other two stances) and ensure that the legs are fully straight right in front of you. This will be your starting position.","As you exhale, pull the machine lever as far as possible to the back of your thighs by flexing at the knees. Keep your torso stationary at all times. Hold the contracted position for a second.","Slowly return to the starting position as you breathe in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Machine', '/exercises/seated-leg-curl/0.jpg', '/exercises/seated-leg-curl/1.jpg'),
  ('Hip Thrust', 'glutes', 'full_gym', 'intermediate', '{}', '{"calves","hamstrings"}', '{"Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise.","Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it.","Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position."}', 'compound', 'Barbell', '/exercises/hip-thrust/0.jpg', '/exercises/hip-thrust/1.jpg'),
  ('Glute Bridge', 'glutes', 'bodyweight', 'beginner', '{}', '{"hamstrings"}', '{"Lie flat on the floor on your back with the hands by your side and your knees bent. Your feet should be placed around shoulder width. This will be your starting position.","Pushing mainly with your heels, lift your hips off the floor while keeping your back straight. Breathe out as you perform this part of the motion and hold at the top for a second.","Slowly go back to the starting position as you breathe in."}', 'isolation', 'Bodyweight', '/exercises/glute-bridge/0.jpg', '/exercises/glute-bridge/1.jpg'),
  ('Standing Calf Raise', 'calves', 'full_gym', 'beginner', '{}', '{}', '{"Adjust the padded lever of the calf raise machine to fit your height.","Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.","Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.","Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Machine', '/exercises/standing-calf-raise/0.jpg', '/exercises/standing-calf-raise/1.jpg'),
  ('Seated Calf Raise', 'calves', 'full_gym', 'beginner', '{}', '{}', '{"Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter.","Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward.","Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position.","Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement.","Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Machine', '/exercises/seated-calf-raise/0.jpg', '/exercises/seated-calf-raise/1.jpg'),
  ('Plank', 'core', 'bodyweight', 'beginner', '{}', '{}', '{"Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.","Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."}', 'isolation', 'Bodyweight', '/exercises/plank/0.jpg', '/exercises/plank/1.jpg'),
  ('Hanging Leg Raise', 'core', 'bodyweight', 'expert', '{}', '{}', '{"Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.","Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.","Go back slowly to the starting position as you breathe in.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Bodyweight', '/exercises/hanging-leg-raise/0.jpg', '/exercises/hanging-leg-raise/1.jpg'),
  ('Cable Crunch', 'core', 'full_gym', 'beginner', '{}', '{}', '{"Kneel below a high pulley that contains a rope attachment.","Grasp cable rope attachment and lower the rope until your hands are placed next to your face.","Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.","With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second.","Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Cable', '/exercises/cable-crunch/0.jpg', '/exercises/cable-crunch/1.jpg'),
  ('Crunch', 'core', 'bodyweight', 'beginner', '{}', '{}', '{"Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.","Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don''t lock your fingers behind your head.","While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.","Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don''t cheat yourself by using momentum.","After the one second contraction, begin to come down slowly again to the starting position as you inhale.","Repeat for the recommended amount of repetitions."}', 'isolation', 'Bodyweight', '/exercises/crunch/0.jpg', '/exercises/crunch/1.jpg'),
  ('Bicycle Crunch', 'core', 'bodyweight', 'beginner', '{}', '{}', '{"Lie flat on the floor with your lower back pressed to the ground. For this exercise, you will need to put your hands beside your head. Be careful however to not strain with the neck as you perform it. Now lift your shoulders into the crunch position.","Bring knees up to where they are perpendicular to the floor, with your lower legs parallel to the floor. This will be your starting position.","Now simultaneously, slowly go through a cycle pedal motion kicking forward with the right leg and bringing in the knee of the left leg. Bring your right elbow close to your left knee by crunching to the side, as you breathe out.","Go back to the initial position as you breathe in.","Crunch to the opposite side as you cycle your legs and bring closer your left elbow to your right knee and exhale.","Continue alternating in this manner until all of the recommended repetitions for each side have been completed."}', 'compound', 'Bodyweight', '/exercises/bicycle-crunch/0.jpg', '/exercises/bicycle-crunch/1.jpg'),
  ('Russian Twist', 'core', 'bodyweight', 'intermediate', '{}', '{"back"}', '{"Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.","Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position.","Twist your torso to the right side until your arms are parallel with the floor while breathing out.","Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side.","Repeat for the recommended amount of repetitions."}', 'compound', 'Bodyweight', '/exercises/russian-twist/0.jpg', '/exercises/russian-twist/1.jpg')
on conflict (name) do update set
  primary_muscle = excluded.primary_muscle,
  equipment = excluded.equipment,
  difficulty = excluded.difficulty,
  cues = excluded.cues,
  secondary_muscles = excluded.secondary_muscles,
  instructions = excluded.instructions,
  mechanic = excluded.mechanic,
  equipment_name = excluded.equipment_name,
  image_url = excluded.image_url,
  image_url_2 = excluded.image_url_2,
  video_url = null;

create table if not exists public.workout_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  days_per_week integer not null check (days_per_week between 2 and 6),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.plan_exercises (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.workout_plans(id) on delete cascade,
  day_number integer not null,
  day_focus text,
  exercise_id uuid not null references public.exercises(id),
  sets integer not null default 3 check (sets > 0),
  rep_min integer not null default 8,
  rep_max integer not null default 12,
  rest_seconds integer not null default 90,
  sort_order integer not null default 0
);

alter table public.plan_exercises add column if not exists day_focus text;

-- Let a library refresh remove exercises that plans still point at.
alter table public.plan_exercises drop constraint if exists plan_exercises_exercise_id_fkey;
alter table public.plan_exercises
  add constraint plan_exercises_exercise_id_fkey
  foreign key (exercise_id) references public.exercises(id) on delete cascade;

delete from public.exercises where name not in ('Barbell Bench Press', 'Incline Barbell Press', 'Dumbbell Bench Press', 'Incline Dumbbell Press', 'Dumbbell Fly', 'Cable Crossover', 'Machine Chest Press', 'Push-Up', 'Wide Push-Up', 'Deadlift', 'Bent-Over Barbell Row', 'One-Arm Dumbbell Row', 'Seated Cable Row', 'Lat Pulldown', 'Close-Grip Pulldown', 'Straight-Arm Pulldown', 'Pull-Up', 'Chin-Up', 'T-Bar Row', 'Overhead Barbell Press', 'Dumbbell Shoulder Press', 'Arnold Press', 'Dumbbell Lateral Raise', 'Front Raise', 'Reverse Fly', 'Face Pull', 'Barbell Shrug', 'Dumbbell Shrug', 'Triceps Pushdown', 'Rope Triceps Pushdown', 'Overhead Rope Extension', 'Close-Grip Bench Press', 'Skull Crusher', 'Lying Dumbbell Extension', 'Overhead Dumbbell Extension', 'Triceps Kickback', 'Bench Dip', 'Triceps Dip', 'Barbell Curl', 'Dumbbell Curl', 'Alternating Dumbbell Curl', 'Hammer Curl', 'Preacher Curl', 'Incline Dumbbell Curl', 'Concentration Curl', 'Cable Curl', 'Spider Curl', 'Back Squat', 'Front Squat', 'Goblet Squat', 'Bodyweight Squat', 'Leg Press', 'Leg Extension', 'Walking Lunge', 'Reverse Lunge', 'Romanian Deadlift', 'Lying Leg Curl', 'Seated Leg Curl', 'Hip Thrust', 'Glute Bridge', 'Standing Calf Raise', 'Seated Calf Raise', 'Plank', 'Hanging Leg Raise', 'Cable Crunch', 'Crunch', 'Bicycle Crunch', 'Russian Twist');

create table if not exists public.body_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  logged_at date not null default current_date,
  weight_kg numeric not null check (weight_kg > 0),
  body_fat_percent numeric check (body_fat_percent between 0 and 100),
  waist_cm numeric,
  chest_cm numeric,
  arms_cm numeric,
  photo_path text,
  created_at timestamptz not null default now()
);

-- One weigh-in per day per user, so re-logging the same day updates in place.
create unique index if not exists body_logs_user_day_idx
  on public.body_logs (user_id, logged_at);

create table if not exists public.workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_date date not null default current_date,
  title text not null,
  duration_minutes integer,
  status text not null default 'completed' check (status in ('planned', 'in_progress', 'completed', 'skipped')),
  created_at timestamptz not null default now()
);

create table if not exists public.session_sets (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.workout_sessions(id) on delete cascade,
  exercise_name text not null,
  set_number integer not null,
  reps integer not null check (reps > 0),
  weight_kg numeric not null default 0 check (weight_kg >= 0),
  rpe numeric check (rpe between 1 and 10),
  created_at timestamptz not null default now()
);

alter table public.body_logs enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.session_sets enable row level security;
alter table public.user_preferences enable row level security;
alter table public.workout_plans enable row level security;
alter table public.plan_exercises enable row level security;
alter table public.exercises enable row level security;

drop policy if exists "Users can manage their preferences" on public.user_preferences;
drop policy if exists "Users can manage their body logs" on public.body_logs;
drop policy if exists "Users can manage their sessions" on public.workout_sessions;
drop policy if exists "Users can manage their plans" on public.workout_plans;
drop policy if exists "Users can manage exercises in their plans" on public.plan_exercises;
drop policy if exists "Authenticated users can read exercises" on public.exercises;
drop policy if exists "Users can manage their session sets" on public.session_sets;

create policy "Users can manage their preferences" on public.user_preferences for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage their body logs" on public.body_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage their sessions" on public.workout_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage their plans" on public.workout_plans for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage exercises in their plans" on public.plan_exercises for all using (
  exists (select 1 from public.workout_plans where id = plan_id and user_id = auth.uid())
) with check (
  exists (select 1 from public.workout_plans where id = plan_id and user_id = auth.uid())
);
create policy "Authenticated users can read exercises" on public.exercises for select using (auth.uid() is not null);
create policy "Users can manage their session sets" on public.session_sets for all using (
  exists (select 1 from public.workout_sessions where id = session_id and user_id = auth.uid())
) with check (
  exists (select 1 from public.workout_sessions where id = session_id and user_id = auth.uid())
);
